repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0f34924c4110aca2294a4e4204aac7b3e31803fb # 0.12.7
    hooks:
      - id: uv-lock

  - repo: https://github.com/ninoseki/uv-sort
    rev: 5164b1c56d16ad34014d74e8cc4bcc4494664059 # v0.7.1
    hooks:
      - id: uv-sort
        files: ^(pyproject\.toml)$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49 # v0.16.5
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
